CREATE TABLE IF NOT EXISTS `custom_weapon` (
  `item_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` varchar(120) NOT NULL DEFAULT '0',
  `additionalname` varchar(120) NOT NULL DEFAULT '',
  `bodypart` varchar(15) NOT NULL DEFAULT 'none',
  `crystallizable` enum('true','false') NOT NULL DEFAULT 'false',
  `weight` smallint(4) NOT NULL DEFAULT '0',
  `soulshots` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `spiritshots` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `material` varchar(11) NOT NULL DEFAULT 'wood',
  `crystal_type` varchar(4) NOT NULL DEFAULT 'none',
  `p_dam` smallint(4) NOT NULL DEFAULT '0',
  `rnd_dam` smallint(3) NOT NULL DEFAULT '0',
  `weaponType` varchar(10) NOT NULL DEFAULT 'none',
  `critical` smallint(3) NOT NULL DEFAULT '0',
  `hit_modify` tinyint(2) NOT NULL DEFAULT '0',
  `avoid_modify` tinyint(2) NOT NULL DEFAULT '0',
  `shield_def` smallint(4) NOT NULL DEFAULT '0',
  `shield_def_rate` smallint(3) NOT NULL DEFAULT '0',
  `atk_speed` smallint(4) NOT NULL DEFAULT '0',
  `mp_consume` tinyint(1) NOT NULL DEFAULT '0',
  `m_dam` smallint(4) NOT NULL DEFAULT '0',
  `duration` mediumint(5) NOT NULL DEFAULT '-1', -- duration in minutes for shadow items
  `time` mediumint(5) NOT NULL DEFAULT '-1',     -- duration in minutes for time limited items
  `price` int(10) unsigned NOT NULL DEFAULT '0',
  `crystal_count` smallint(4) unsigned NOT NULL DEFAULT '0',
  `sellable` enum('true','false') NOT NULL DEFAULT 'false',
  `dropable` enum('true','false') NOT NULL DEFAULT 'false',
  `destroyable` enum('true','false') NOT NULL DEFAULT 'false',
  `tradeable` enum('true','false') NOT NULL DEFAULT 'false',
  `depositable` enum('true','false') NOT NULL DEFAULT 'false',
  `enchant4_skill_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `enchant4_skill_lvl` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `onCast_skill_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `onCast_skill_lvl` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `onCast_skill_chance` smallint(3) NOT NULL DEFAULT '0',
  `onCrit_skill_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `onCrit_skill_lvl` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `onCrit_skill_chance` smallint(3) NOT NULL DEFAULT '0',
  `change_weaponId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `skill` varchar(70) NOT NULL DEFAULT '0-0;',
  PRIMARY KEY (`item_id`)
);