ALTER TABLE `custom_armor` MODIFY `name` varchar(120) NOT NULL default '';
ALTER TABLE `custom_armor` MODIFY `bodypart` varchar(15) NOT NULL default 'none';
ALTER TABLE `custom_armor` MODIFY `crystallizable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_armor` MODIFY `armor_type` varchar(5) NOT NULL default 'none';
ALTER TABLE `custom_armor` MODIFY `material` varchar(15) NOT NULL default 'wood';
ALTER TABLE `custom_armor` MODIFY `crystal_type` varchar(4) NOT NULL default 'none';
ALTER TABLE `custom_armor` MODIFY `duration` int(3) NOT NULL default '-1';
ALTER TABLE `custom_armor` MODIFY `time` int(4) NOT NULL default '-1';
ALTER TABLE `custom_armor` MODIFY `crystal_count` int(4) NOT NULL default '0';
ALTER TABLE `custom_armor` MODIFY `sellable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_armor` MODIFY `dropable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_armor` MODIFY `destroyable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_armor` MODIFY `tradeable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_armorsets` ADD `mw_legs` SMALLINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `custom_armorsets` ADD `mw_head` SMALLINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `custom_armorsets` ADD `mw_gloves` SMALLINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `custom_armorsets` ADD `mw_feet` SMALLINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `custom_armorsets` ADD `mw_shield` SMALLINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `custom_etcitem` MODIFY `item_id` decimal(11,0) NOT NULL default '0';
ALTER TABLE `custom_etcitem` MODIFY `name` varchar(100) NOT NULL default '';
ALTER TABLE `custom_etcitem` MODIFY `crystallizable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_etcitem` MODIFY `item_type` varchar(14) NOT NULL default 'none';
ALTER TABLE `custom_etcitem` MODIFY `weight` decimal(4,0) NOT NULL default '0';
ALTER TABLE `custom_etcitem` MODIFY `consume_type` varchar(9) NOT NULL default 'normal';
ALTER TABLE `custom_etcitem` MODIFY `material` varchar(11) NOT NULL default 'wood';
ALTER TABLE `custom_etcitem` MODIFY `duration` int(3) NOT NULL default '-1';
ALTER TABLE `custom_etcitem` MODIFY `time` int(4) NOT NULL default '-1';
ALTER TABLE `custom_etcitem` MODIFY `price` decimal(11,0) NOT NULL default '0';
ALTER TABLE `custom_etcitem` MODIFY `crystal_count` int(4) NOT NULL default '0';
ALTER TABLE `custom_etcitem` MODIFY `sellable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_etcitem` MODIFY `dropable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_etcitem` MODIFY `destroyable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_etcitem` MODIFY `tradeable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_etcitem` MODIFY `skill` varchar(70) NOT NULL default '0-0;';
ALTER TABLE `custom_etcitem` MODIFY `html` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `name` varchar(120) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY`bodypart` varchar(15) NOT NULL default '';
ALTER TABLE `custom_weapon` MODIFY `crystallizable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `weight` decimal(4,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `soulshots` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `spiritshots` decimal(1,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `material` varchar(11) NOT NULL default 'wood';
ALTER TABLE `custom_weapon` MODIFY `crystal_type` varchar(4) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `p_dam` decimal(5,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `rnd_dam` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `weaponType` varchar(10) NOT NULL default '';
ALTER TABLE `custom_weapon` MODIFY `critical` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `hit_modify` decimal(6,5) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `avoid_modify` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `shield_def` decimal(3,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `shield_def_rate` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `atk_speed` decimal(3,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `mp_consume` decimal(2,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `m_dam` decimal(3,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `duration` int(3) NOT NULL default '-1';
ALTER TABLE `custom_weapon` MODIFY `time` int(4) NOT NULL default '-1';
ALTER TABLE `custom_weapon` MODIFY `price` decimal(11,0) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `crystal_count` int(4) NOT NULL default '0';
ALTER TABLE `custom_weapon` MODIFY `sellable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `dropable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `destroyable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `tradeable` varchar(5) NOT NULL default 'false';
ALTER TABLE `custom_weapon` MODIFY `skill` varchar(70) NOT NULL default '0-0;';