ALTER TABLE `character_offline_trade_items`
MODIFY COLUMN `charId`  int(10) UNSIGNED NOT NULL DEFAULT 0 FIRST ,
MODIFY COLUMN `item`  int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `charId`,
MODIFY COLUMN `count`  bigint(20) UNSIGNED NOT NULL DEFAULT 0 AFTER `item`,
MODIFY COLUMN `price`  bigint(20) UNSIGNED NOT NULL DEFAULT 0 AFTER `count`,
DROP PRIMARY KEY;