CREATE TABLE IF NOT EXISTS `custom_weapon` (
  `item_id` decimal(11,0) NOT NULL default '0',
  `name` varchar(120) NOT NULL default '0',
  `bodypart` varchar(15) NOT NULL default '',
  `crystallizable` varchar(5) NOT NULL default 'false',
  `weight` decimal(4,0) NOT NULL default '0',
  `soulshots` decimal(2,0) NOT NULL default '0',
  `spiritshots` decimal(1,0) NOT NULL default '0',
  `material` varchar(11) NOT NULL default 'wood',
  `crystal_type` varchar(4) NOT NULL default '0',
  `p_dam` decimal(5,0) NOT NULL default '0',
  `rnd_dam` decimal(2,0) NOT NULL default '0',
  `weaponType` varchar(10) NOT NULL default '',
  `critical` decimal(2,0) NOT NULL default '0',
  `hit_modify` decimal(6,5) NOT NULL default '0',
  `avoid_modify` decimal(2,0) NOT NULL default '0',
  `shield_def` decimal(3,0) NOT NULL default '0',
  `shield_def_rate` decimal(2,0) NOT NULL default '0',
  `atk_speed` decimal(3,0) NOT NULL default '0',
  `mp_consume` decimal(2,0) NOT NULL default '0',
  `m_dam` decimal(3,0) NOT NULL default '0',
  `duration` int(3) NOT NULL default '-1',    -- duration for shadow items
  `time` int(4) NOT NULL default '-1',              -- duration for time limited items
  `price` decimal(11,0) NOT NULL default '0',
  `crystal_count` int(4) NOT NULL default '0',
  `sellable` varchar(5) NOT NULL default 'false',
  `dropable` varchar(5) NOT NULL default 'false',
  `destroyable` varchar(5) NOT NULL default 'false',
  `tradeable` varchar(5) NOT NULL default 'false',
  `depositable` varchar(5) NOT NULL default 'false',
  `enchant4_skill_id` decimal(11,0) NOT NULL default '0',
  `enchant4_skill_lvl` decimal(11,0) NOT NULL default '0',
  `onCast_skill_id` decimal(11,0) NOT NULL default '0',
  `onCast_skill_lvl` decimal(11,0) NOT NULL default '0',
  `onCast_skill_chance` decimal(11,0) NOT NULL default '0',
  `onCrit_skill_id` decimal(11,0) NOT NULL default '0',
  `onCrit_skill_lvl` decimal(11,0) NOT NULL default '0',
  `onCrit_skill_chance` decimal(11,0) NOT NULL default '0',
  `change_weaponId` decimal(11,0) NOT NULL default '0',
  `skill` varchar(70) NOT NULL default '0-0;',
  PRIMARY KEY (`item_id`)
);